# Generated by Django 4.1.4 on 2023-10-14 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('displayName', models.CharField(max_length=255)),
                ('github', models.URLField(max_length=2048, null=True)),
                ('host', models.URLField(max_length=2048)),
                ('profileImage', models.URLField(max_length=2048)),
                ('url', models.URLField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.BinaryField(blank=True, max_length=4096, null=True)),
                ('contentType', models.CharField(choices=[('B64', 'application/base64'), ('JPEG', 'image/jpeg;base64'), ('MD', 'text/markdown'), ('PL', 'text/plain'), ('PNG', 'image/png;base64')], default='PL', max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('title', models.TextField(max_length=255)),
                ('source', models.URLField(max_length=2048)),
                ('origin', models.URLField(max_length=255)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('visibility', models.TextField(default='PUBLIC')),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.author')),
                ('categories', models.ManyToManyField(blank=True, to='socialdistribution.category')),
            ],
        ),
    ]
    migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('contentType', models.TextField(default="text/plain", editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.author')),
                ('comment', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.post')),
            ],
        )
