# Generated by Django 4.1.4 on 2023-10-30 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('displayName', models.CharField(max_length=255)),
                ('github', models.URLField(max_length=2048, null=True)),
                ('host', models.URLField(max_length=2048)),
                ('profileImage', models.URLField(max_length=2048)),
                ('url', models.URLField(max_length=2048)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.BinaryField(blank=True, max_length=4096, null=True)),
                ('contentType', models.CharField(choices=[('application/base64', 'Base64'), ('image/jpeg;base64', 'Jpeg'), ('text/markdown', 'Markdown'), ('text/plain', 'Plain'), ('image/png;base64', 'Png'), ('image/webp;base64', 'Webp')], default='text/plain', max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('title', models.TextField(max_length=255)),
                ('source', models.URLField(max_length=2048)),
                ('origin', models.URLField(max_length=255)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('visibility', models.TextField(default='PUBLIC')),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.author')),
                ('categories', models.ManyToManyField(blank=True, to='socialdistribution.category')),
            ],
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.author')),
                ('items', models.ManyToManyField(to='socialdistribution.inboxitem')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_author', models.JSONField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.author')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.JSONField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.author')),
            ],
        ),
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.UniqueConstraint(fields=('author', 'follower_author'), name='unique_follower'),
        ),
    ]
