# Generated by Django 4.1.4 on 2023-11-20 11:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('socialdistribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.TextField(default='comment', editable=False)),
                ('author', models.JSONField()),
                ('comment', models.TextField(max_length=255)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('contentType', models.TextField(default='text/plain', editable=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.post')),
            ],
        ),
        migrations.AddField(
            model_name='inboxitem',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.TextField(default='https://www.w3.org/ns/activitystreams', editable=False)),
                ('type', models.TextField(default='Like', editable=False)),
                ('author', models.JSONField()),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.post')),
            ],
        ),
    ]
