# Generated by Django 4.1.4 on 2023-10-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0002_alter_author_id_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('application/base64', 'Base64'), ('image/jpeg;base64', 'Jpeg'), ('text/markdown', 'Markdown'), ('text/plain', 'Plain'), ('image/png;base64', 'Png')], default='text/plain', max_length=255),
        ),
    ]
