# Generated by Django 4.1.4 on 2023-10-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0004_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('application/base64', 'Base64'), ('image/jpeg;base64', 'Jpeg'), ('text/markdown', 'Markdown'), ('text/plain', 'Plain'), ('image/png;base64', 'Png'), ('image/webp;base64', 'Webp')], default='text/plain', max_length=255),
        ),
    ]
