# Generated by Django 4.2.6 on 2023-10-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0006_inboxitem_inbox_follower_follow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(max_length=4096),
        ),
    ]
