# Generated by Django 4.1.4 on 2023-11-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0006_inboxitem_inbox_follower_follow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_allowed', models.BooleanField(default=True)),
            ],
        ),
    ]
