# Generated by Django 4.1.4 on 2023-11-20 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0007_node'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='is_allowed',
            new_name='is_active',
        ),
    ]
