# Generated by Django 4.1.4 on 2023-11-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0008_rename_is_allowed_node_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
