# Generated by Django 4.2.6 on 2023-10-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0008_alter_author_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
