# Generated by Django 4.1.4 on 2023-11-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0009_node_is_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
