# Generated by Django 4.1.4 on 2023-11-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('socialdistribution', '0010_alter_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
