# Generated by Django 4.1.4 on 2023-11-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0011_inboxitem_json_data_alter_inboxitem_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.JSONField(),
        ),
    ]
