# Generated by Django 4.1.4 on 2023-11-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0010_alter_node_is_authenticated'),
        ('socialdistribution', '0012_alter_comment_author_alter_like_author'),
    ]

    operations = [
    ]
