# Generated by Django 4.1.4 on 2023-11-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0012_alter_comment_author_alter_like_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
